version: '3.12'

services:
  web:
    container_name: stock-exchange-dashboard
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ["/app/entrypoint.sh"]
    env_file:
      - ./envs/.env
